# Generated by Django 3.0.14 on 2022-05-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220503_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='file_format',
            name='file_format',
        ),
        migrations.AddField(
            model_name='book',
            name='book_format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.File_format'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
