# Generated by Django 3.0.14 on 2022-05-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_format',
            new_name='FileFormat',
        ),
    ]
