# Generated by Django 3.0.14 on 2022-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220516_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drukarka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_format',
            new_name='BookFormat',
        ),
        migrations.AddField(
            model_name='fileformat',
            name='book_format',
            field=models.CharField(choices=[('HCP', ' Druk/papier w twardej okładce '), ('SCP', ' Druk/papier w miękkiej okładce'), ('epub', 'e-publikacja'), ('pdf', 'pdf jaki jest każdy widzi')], default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='condition',
            field=models.TextField(verbose_name='max_length = 50'),
        ),
    ]
