# Generated by Django 3.0.14 on 2022-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220522_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.CharField(max_length=300),
        ),
    ]
