# Generated by Django 3.0.14 on 2022-05-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220522_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('5.0', ' Wspaniała'), ('4.0', ' Dobra'), ('3.0', 'Przeciętna'), ('2.0', 'Słaba'), ('1.0', 'Zła')], default='1.0', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='book_format',
            field=models.CharField(choices=[('HCP', ' Druk/papier w twardej okładce '), ('SCP', ' Druk/papier w miękkiej okładce'), ('epub', 'e-publikacja'), ('pdf', 'pdf jaki jest każdy widzi')], default='pdf', max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, to='blog.Rate'),
            preserve_default=False,
        ),
    ]
